// Listing::SUBCATEGORIES on the API, keyed by category, with their labels.
export const SUBCATEGORY_LABELS: Record<string, Record<string, string>> = {
  waste_streams: {
    post_industrial_waste: "Post-industrial waste",
    post_consumer_waste: "Post-consumer waste",
    deadstock: "Deadstock",
    production_offcuts: "Production off-cuts",
  },
  raw_materials: {
    natural_fibres: "Natural fibres",
    recycled_fibres: "Recycled fibres",
    synthetic_fibres: "Synthetic fibres",
    yarns_threads: "Yarns & threads",
  },
  intermediate_materials: {
    greige_fabric: "Greige fabric",
    finished_fabric: "Finished fabric",
    trimmings_accessories: "Trimmings & accessories",
    technical_substrates: "Technical substrates",
  },
  certified_materials: {
    organic_certified: "Organic certified (GOTS)",
    recycled_certified: "Recycled certified (GRS)",
    fair_trade: "Fair trade",
    bio_based: "Bio-based & innovative",
  },
  equipment: {
    sewing_assembly: "Sewing & assembly machines",
    cutting_spreading: "Cutting & spreading machines",
    knitting_machines: "Knitting machines",
    weaving_looms: "Weaving looms",
    dyeing_finishing: "Dyeing & finishing equipment",
    sorting_grading: "Sorting & grading equipment",
    embroidery_machines: "Embroidery machines",
  },
  facilities: {
    production_workshop: "Production workshop",
    storage_warehouse: "Storage & warehouse",
    showroom: "Showroom",
    collection_point: "Collection & drop-off point",
    photography_studio: "Photography studio",
  },
  open_spaces: { fablab: "Fablab", shared_atelier: "Shared atelier / makerspace", coworking_space: "Coworking space" },
  workforce: {
    traditional_craft: "Traditional craft techniques",
    industrial_techniques: "Industrial techniques",
    material_expertise: "Material expertise",
    mentoring: "Mentoring & knowledge transfer",
    seasonal_workforce: "Seasonal / temporary workforce",
  },
  financing_programs: {
    subsidies_grants: "Subsidies & grants",
    incubation_acceleration: "Incubation & acceleration",
    circular_economy_funds: "Circular economy funds",
    micro_financing: "Micro-financing",
  },
  production_manufacturing: {
    cut_sew: "Cut & sew",
    knitting_weaving: "Knitting & weaving",
    embroidery_finishing: "Embroidery & finishing",
    dyeing_printing: "Dyeing & printing",
    upcycling_transformation: "Upcycling & transformation",
    repair_alteration: "Repair & alteration",
  },
  sorting_processing: {
    waste_sorting: "Waste sorting & grading",
    fibre_recovery: "Fibre recovery & separation",
    shredding_grinding: "Shredding & grinding",
    quality_assessment: "Quality assessment",
  },
  design_development: {
    fashion_textile_design: "Fashion & textile design",
    pattern_making: "Pattern making",
    prototype_development: "Prototype development",
    material_research: "Material research & development",
  },
  logistics_collection: {
    waste_collection: "Waste collection & pick-up",
    transport_delivery: "Transport & delivery",
    warehousing: "Warehousing",
  },
  consulting_training: {
    circular_economy_strategy: "Circular economy strategy",
    life_cycle_assessment: "Life cycle assessment (LCA)",
    training_workshops: "Training & workshops",
    impact_measurement: "Impact measurement",
  },
  certification_auditing: {
    gots_certification: "GOTS certification",
    oeko_tex: "OEKO-TEX",
    grs_certification: "GRS (Global Recycled Standard)",
    social_auditing: "Social auditing",
    environmental_auditing: "Environmental auditing",
    other_certification: "Other certification",
  },
  end_of_life: {
    reuse_redistribution: "Reuse & redistribution",
    donation_programs: "Donation programs",
    take_back_schemes: "Take-back schemes",
    disassembly: "Disassembly & component recovery",
  },
  apparel_accessories: { garments: "Garments", accessories: "Accessories", footwear: "Footwear", sportswear: "Sportswear" },
  home_living: { home_textiles: "Home textiles", interior_furnishings: "Interior furnishings", bedding_linen: "Bedding & linen" },
  technical_industrial: {
    technical_textiles: "Technical textiles",
    industrial_fabrics: "Industrial fabrics",
    geotextiles: "Geotextiles",
    medical_textiles: "Medical textiles",
  },
  upcycled_circular: {
    upcycled_products: "Upcycled products",
    repaired_restored: "Repaired / restored items",
    zero_waste_collections: "Zero-waste collections",
  },
  retail_resale: {
    brick_and_mortar: "Brick & mortar stores",
    pop_up_shops: "Pop-up shops",
    thrift_vintage: "Thrift & vintage shops",
    charity_shops: "Charity shops",
  },
  wholesale: { b2b_wholesale: "B2B wholesale", bulk_sourcing: "Bulk sourcing", trade_fairs: "Trade fairs & showrooms" },
  ecommerce_platforms: {
    online_marketplace: "Online marketplace",
    resale_platform: "Resale platform",
    rental_subscription: "Rental & subscription",
  },
};
